// Generated by npm run build. Edit src/core.js and server/sheets.gs instead.
const ERROR_MESSAGE = 'Something went wrong. Please try again. If the issue continues, contact Admin.';
const money = value => `Rs. ${Number(value).toLocaleString('en-LK', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
function today(now = new Date()) {
  const parts = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Colombo', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(now);
  const p = Object.fromEntries(parts.map(x => [x.type, x.value]));
  return `${p.year}-${p.month}-${p.day}`;
}
function dateValue(value) {
  if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value)) throw new Error('Choose a valid date.');
  const n = Date.parse(`${value}T00:00:00Z`);
  if (!Number.isFinite(n) || new Date(n).toISOString().slice(0, 10) !== value) throw new Error('Choose a valid date.');
  return n;
}
function nightsBetween(checkIn, pickup) {
  const nights = (dateValue(pickup) - dateValue(checkIn)) / 86400000;
  if (nights < 1) throw new Error('Pickup must be after check-in.');
  if (nights > 3650) throw new Error('Stay cannot exceed 3,650 nights.');
  return nights;
}
function rateFor(type, count, nights) {
  if (!['dog', 'cat'].includes(type) || !Number.isInteger(count) || count < 1 || count > 50 || !Number.isInteger(nights) || nights < 1 || nights > 3650) throw new Error('Invalid boarding details.');
  if (type === 'dog') return nights >= 30 ? 1850 : count === 1 ? (nights <= 3 ? 3000 : nights <= 6 ? 2500 : 2000) : nights <= 3 ? 2500 : 2000;
  return count === 1 ? (nights <= 3 ? 2000 : 1500) : nights <= 4 ? 1850 : 1500;
}
function textValue(value, label, max = 120, optional = false) {
  if (typeof value !== 'string' || value.trim().length > max || (!optional && !value.trim())) throw new Error(`Enter ${label}.`);
  return value.trim();
}
function calculateReceipt(input) {
  const customerName = textValue(input.customerName, 'customer name');
  const contactNumber = textValue(input.contactNumber ?? '', 'a valid contact number', 30, true);
  if (contactNumber && !/^[+\d\s().-]{5,30}$/.test(contactNumber)) throw new Error('Enter a valid contact number.');
  const nights = nightsBetween(input.checkInDate, input.pickupDate);
  if (!Array.isArray(input.pets) || input.pets.length < 1 || input.pets.length > 50) throw new Error('Add between 1 and 50 pets.');
  const pets = input.pets.map(p => ({ type: ['dog', 'cat'].includes(p.type) ? p.type : (() => { throw new Error('Choose dog or cat.'); })(), name: textValue(p.name, 'each pet name', 80) }));
  const lines = ['dog', 'cat'].flatMap(type => {
    const count = pets.filter(p => p.type === type).length;
    if (!count) return [];
    const rate = rateFor(type, count, nights);
    return [{ type, count, nights, rate, total: count * nights * rate }];
  });
  const standardTotal = lines.reduce((sum, x) => sum + x.total, 0);
  return { customerName, contactNumber, pets, checkInDate: input.checkInDate, pickupDate: input.pickupDate, nights, lines, standardTotal, finalTotal: standardTotal, pricingVersion: '2026-09-v1' };
}
function cents(value) {
  if (!/^(0|[1-9]\d{0,8})(\.\d{1,2})?$/.test(String(value))) throw new Error('Enter a positive amount with up to 2 decimal places.');
  const n = Math.round(Number(value) * 100);
  if (!Number.isSafeInteger(n)) throw new Error('Amount is too large.');
  return n;
}
function calculateAccounts(input, currentDate = today()) {
  dateValue(input.date);
  if (input.date > currentDate) throw new Error('Accounts date cannot be in the future.');
  const opening = cents(input.openingCash);
  if (!Array.isArray(input.transactions) || input.transactions.length > 200) throw new Error('Use at most 200 transactions.');
  const transactions = input.transactions.map(t => {
    if (!['IN', 'OUT'].includes(t.type)) throw new Error('Choose Cash In or Cash Out.');
    const amount = cents(t.amount);
    if (!amount) throw new Error('Transaction amounts must be greater than zero.');
    return { type: t.type, description: textValue(t.description, 'a transaction description', 200), amount: amount / 100 };
  });
  const total = type => transactions.filter(t => t.type === type).reduce((sum, t) => sum + Math.round(t.amount * 100), 0);
  return { date: input.date, openingCash: opening / 100, transactions, totalCashIn: total('IN') / 100, totalCashOut: total('OUT') / 100, expectedCash: (opening + total('IN') - total('OUT')) / 100 };
}

// Google Apps Script adapter. Deploy generated Code.gs, with the Sheets advanced service enabled.
const HEADERS = {
  Receipts: ['ReceiptID','CreatedDate','CreatedAt','CreatedBy','Username','CustomerName','ContactNumber','PetsJSON','CheckInDate','PickupDate','Nights','LinesJSON','StandardTotal','FinalTotal','PricingVersion','RequestID','RequestHash'],
  'Account Days': ['AccountDayID','Date','OpeningCash','TotalCashIn','TotalCashOut','ExpectedCash','Submitted','SubmittedAt','CreatedBy','Username','RequestID','RequestHash'],
  'Account Transactions': ['TransactionID','AccountDayID','Date','Type','Description','Amount']
};
function setup() {
  const ss = SpreadsheetApp.openById(PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID'));
  ss.setSpreadsheetTimeZone('Asia/Colombo');
  Object.keys(HEADERS).forEach(name => {
    const sheet = ss.getSheetByName(name) || ss.insertSheet(name);
    if (sheet.getLastRow() === 0) sheet.appendRow(HEADERS[name]);
    else if (JSON.stringify(sheet.getRange(1,1,1,HEADERS[name].length).getValues()[0]) !== JSON.stringify(HEADERS[name])) throw new Error('Header mismatch: ' + name);
    sheet.setFrozenRows(1);
  });
}
function doPost(e) {
  let lock;
  try {
    if (!e.postData || e.postData.contents.length > 150000) throw new Error('SIZE');
    const envelope = JSON.parse(e.postData.contents);
    const props = PropertiesService.getScriptProperties();
    const secret = props.getProperty('SHARED_SECRET');
    if (!secret || secret.length < 32 || typeof envelope.payload !== 'string') throw new Error('CONFIG');
    const expected = Utilities.computeHmacSha256Signature(envelope.payload, secret).map(b => ((b + 256) % 256).toString(16).padStart(2,'0')).join('');
    const signature = String(envelope.signature || '');
    let difference = expected.length ^ signature.length;
    for (let i = 0; i < expected.length; i++) difference |= expected.charCodeAt(i) ^ (signature.charCodeAt(i) || 0);
    if (difference) throw new Error('SIGNATURE');
    const request = JSON.parse(envelope.payload);
    if (!Number.isFinite(request.timestamp) || Math.abs(Date.now() - request.timestamp) > 120000) throw new Error('EXPIRED');
    if (!request.createdBy || !request.username) throw new Error('IDENTITY');
    const ss = SpreadsheetApp.openById(props.getProperty('SPREADSHEET_ID'));
    lock = LockService.getScriptLock();
    lock.waitLock(20000);
    const data = executeRequest(ss, request);
    return output({ ok: true, data });
  } catch (error) {
    return output({ ok: false, code: error.message === 'LOCKED' ? 'LOCKED' : 'ERROR' });
  } finally { if (lock && lock.hasLock()) lock.releaseLock(); }
}
function output(value) { return ContentService.createTextOutput(JSON.stringify(value)).setMimeType(ContentService.MimeType.JSON); }
function rows(ss, name) {
  const sheet = ss.getSheetByName(name);
  if (!sheet) throw new Error('SCHEMA');
  if (JSON.stringify(sheet.getRange(1,1,1,HEADERS[name].length).getValues()[0]) !== JSON.stringify(HEADERS[name])) throw new Error('SCHEMA');
  return sheet.getLastRow() <= 1 ? [] : sheet.getRange(2,1,sheet.getLastRow()-1,HEADERS[name].length).getValues();
}
function appendRequest(ss, name, values) {
  return { appendCells: { sheetId: ss.getSheetByName(name).getSheetId(), rows: values.map(row => ({ values: row.map(v => ({ userEnteredValue: typeof v === 'number' ? { numberValue: v } : typeof v === 'boolean' ? { boolValue: v } : { stringValue: String(v ?? '') } })) })), fields: 'userEnteredValue' } };
}
function receiptFrom(row) {
  return { receiptId: row[0], createdDate: row[1], createdAt: row[2], customerName: row[5], contactNumber: row[6], pets: JSON.parse(row[7]), checkInDate: row[8], pickupDate: row[9], nights: row[10], lines: JSON.parse(row[11]), standardTotal: row[12], finalTotal: row[13], pricingVersion: row[14] };
}
function accountFrom(ss, row) {
  return { accountDayId: row[0], date: row[1], openingCash: row[2], totalCashIn: row[3], totalCashOut: row[4], expectedCash: row[5], submitted: row[6] === true, submittedAt: row[7], transactions: rows(ss, 'Account Transactions').filter(t => t[1] === row[0]).map(t => ({ type: t[3], description: t[4], amount: t[5] })) };
}
function executeRequest(ss, request) {
  const { action, data } = request;
  const currentDate = Utilities.formatDate(new Date(), 'Asia/Colombo', 'yyyy-MM-dd');
  if (action === 'receipts.list') { dateValue(data.date); return rows(ss, 'Receipts').filter(r => r[1] === data.date).map(receiptFrom); }
  if (action === 'accounts.get') { dateValue(data.date); const row = rows(ss, 'Account Days').find(r => r[1] === data.date); return row ? accountFrom(ss, row) : null; }
  if (!['receipts.create','accounts.create'].includes(action) || !/^[0-9a-f-]{36}$/i.test(data.requestId || '')) throw new Error('ACTION');
  // Hash the normalized request, binding retries to the same user and payload.
  const hash = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, JSON.stringify([request.createdBy, data])).map(b => ((b+256)%256).toString(16).padStart(2,'0')).join('');
  const timestamp = new Date().toISOString();
  if (action === 'receipts.create') {
    const all = rows(ss, 'Receipts');
    const previous = all.find(r => r[15] === data.requestId);
    if (previous) { if (previous[16] !== hash) throw new Error('REPLAY'); return receiptFrom(previous); }
    const receipt = calculateReceipt(data);
    const prefix = 'UC-' + currentDate.replace(/-/g,'') + '-';
    const next = all.filter(r => String(r[0]).startsWith(prefix)).reduce((max,r) => Math.max(max, Number(String(r[0]).slice(prefix.length)) || 0), 0) + 1;
    const id = prefix + String(next).padStart(3,'0');
    const row = [id,currentDate,timestamp,request.createdBy,request.username,receipt.customerName,receipt.contactNumber,JSON.stringify(receipt.pets),receipt.checkInDate,receipt.pickupDate,receipt.nights,JSON.stringify(receipt.lines),receipt.standardTotal,receipt.finalTotal,receipt.pricingVersion,data.requestId,hash];
    Sheets.Spreadsheets.batchUpdate({ requests: [appendRequest(ss, 'Receipts', [row])] }, ss.getId());
    return receiptFrom(row);
  }
  const all = rows(ss, 'Account Days');
  const previous = all.find(r => r[10] === data.requestId);
  if (previous) { if (previous[11] !== hash) throw new Error('REPLAY'); return accountFrom(ss, previous); }
  const account = calculateAccounts(data, currentDate);
  if (all.some(r => r[1] === account.date)) throw new Error('LOCKED');
  const id = 'UC-AD-' + account.date.replace(/-/g,'');
  const row = [id,account.date,account.openingCash,account.totalCashIn,account.totalCashOut,account.expectedCash,true,timestamp,request.createdBy,request.username,data.requestId,hash];
  const transactions = account.transactions.map((t,i) => [id+'-'+(i+1),id,account.date,t.type,t.description,t.amount]);
  const requests = [appendRequest(ss, 'Account Days', [row])];
  if (transactions.length) requests.push(appendRequest(ss, 'Account Transactions', transactions));
  // One atomic batch: a submitted day can never be saved without all its transactions.
  Sheets.Spreadsheets.batchUpdate({ requests }, ss.getId());
  return { ...account, accountDayId: id, submitted: true, submittedAt: timestamp };
}
