import { mkdir, cp, readFile, writeFile, readdir } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
const modules = (await readdir('src')).filter(name => name.endsWith('.js')).map(name => `src/${name}`);
modules.push('functions/api/portal.js');
for (const file of modules) {
  const result = spawnSync(process.execPath, ['--check', file], { encoding: 'utf8', windowsHide: true });
  if (result.error) throw result.error;
  if (result.status !== 0) throw new Error(result.stderr);
}
await mkdir('dist', { recursive: true });
await cp('public', 'dist', { recursive: true });
await cp('src', 'dist/src', { recursive: true });
const core = (await readFile('src/core.js', 'utf8')).replace(/^export /gm, '');
await mkdir('google-apps-script', { recursive: true });
await writeFile('google-apps-script/Code.gs', '// Generated by npm run build. Edit src/core.js and server/sheets.gs instead.\n' + core + '\n' + await readFile('server/sheets.gs', 'utf8'));
console.log('Built dist/ and google-apps-script/Code.gs');
